DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS words;
DROP TABLE IF EXISTS active_words;
DROP TABLE IF EXISTS players;

CREATE TABLE games (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE words (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  word TEXT UNIQUE NOT NULL
);

CREATE TABLE active_words (
  game_id INTEGER NOT NULL,
  word_id INTEGER NOT NULL,
  color TEXT NOT NULL
);

CREATE TABLE moves (
  game_id INTEGER NOT NULL,
  word_id INTEGER NOT NULL,
  selected_at INTEGER NOT NULL
);

CREATE TABLE players (
  game_id INTEGER NOT NULL,
  username INTEGER NOT NULL,
  kind TEXT NOT NULL
);
